import { WorkspaceData } from "./types";

export const WORKSPACE_REPORT_DB: Record<string, WorkspaceData> = {
  worksmart: {
    attendance: [
      {
        id: "ATT-001",
        name: "Sok Chamroeun",
        role: "Frontend Engineer",
        date: "2026-06-25",
        checkIn: "08:24 AM",
        checkOut: "05:30 PM",
        hours: 8.5,
        status: "Present",
      },
      {
        id: "ATT-002",
        name: "Chan Eliza",
        role: "UI/UX Designer",
        date: "2026-06-25",
        checkIn: "09:15 AM",
        checkOut: "05:00 PM",
        hours: 7.75,
        status: "Late",
      },
      {
        id: "ATT-003",
        name: "Nguon Rotha",
        role: "DevOps Engineer",
        date: "2026-06-25",
        checkIn: "08:02 AM",
        checkOut: "06:00 PM",
        hours: 9.5,
        status: "Present",
      },
      {
        id: "ATT-004",
        name: "Kemp Sophea",
        role: "QA Engineer",
        date: "2026-06-25",
        checkIn: null,
        checkOut: null,
        hours: 0,
        status: "Absent",
      },
    ],
    leaves: [
      {
        id: "LRQ-402",
        name: "Sok Chamroeun",
        type: "Annual Leave",
        start: "2026-07-01",
        end: "2026-07-05",
        days: 5,
        status: "Pending",
      },
      {
        id: "LRQ-409",
        name: "Chan Eliza",
        type: "Sick Leave",
        start: "2026-06-29",
        end: "2026-06-30",
        days: 2,
        status: "Approved",
        attachment: "medical_certificate_eliza.pdf",
      },
      {
        id: "LRQ-395",
        name: "Ouk Somnang",
        type: "Unpaid Leave",
        start: "2026-05-20",
        end: "2026-05-22",
        days: 2,
        status: "Rejected",
      },
    ],
  },
};
